<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "threesixtyslider"
 *
 * Auto generated by Extension Builder 2014-06-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '360 Slider',
	'description' => 'Shows products, models, item as 360 degree slider.',
	'category' => 'plugin',
	'author' => 'Toni Cieslik, Andreas Habel',
	'author_email' => 'tx@dpool.net, andreas.habel@dpool.net',
	'author_company' => 'dpool, dpool',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '6.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>